#!/usr/bin/env python3
# encoding: utf-8

import requests
import io, json
import certifi
import socket
from netifaces import interfaces, ifaddresses, AF_INET

HOSTNAME="MYHOST"   # hostname (including subdomain)
APIKEY="MYAPIKEY"  # DDNSS Token (Accounts > Domain List > Advanced DNS)

def getSystemIP():
    for ifaceName in interfaces():
        addresses = [i['addr'] for i in ifaddresses(ifaceName).setdefault(AF_INET, [{'addr':'No IP addr'}] )]
    return ' '.join(addresses)

def getDnsIP(host):
    host_ip = socket.gethostbyname(host)
    return host_ip

def updateRecord(ip):
    global HOSTNAME
    global APIKEY
    ddns_upd = "https://www.ddnss.de/upd.php"
    url = ddns_upd+"?key=" + APIKEY + "&host=" + HOSTNAME + "&ip=" + ip
    return requests.get(url, verify=certifi.where())

registered_ip = getDnsIP(HOSTNAME)
# print("Registered IP: " + registered_ip)

current_ip = getSystemIP()
# print("External IP: " + current_ip)

result = ''
if registered_ip != current_ip:
    r = updateRecord(current_ip)
    if r.status_code == 200:
        result = "[UPDATE] successfully update host [" + HOSTNAME +"] to IP [" + current_ip +"]"
    else:
        result = "[ERROR] API error\n" + r.content
else:
    result = "[SKIPPED] IP already registered - not changed"

print(result)
